### ISSUE TITLE
roff preview?

### ISSUE THREAD

**Issue by bronson** [Alhadis/language-roff#3]
The screenshot in the README makes me think you have a preview mode that I can see in Atom?  I'm looking for something like the continually-updated Markdown Preview.

Looking at the code, though...  I guess this plugin contains syntax files and snippets, and I still need to escape to the terminal to preview?

**Comment by Alhadis** [comment]
I suppose I could always make one. Wouldn't be terribly hard, I think. Just a case of piping Groff's output to Atom like a postprocessor. :)

**Comment by Alhadis** [comment]
I'll see what I can do, mate.

**Comment by Alhadis** [comment]
Hey @bronson, just letting you know I've not forgotten about this. :) Trying to get work finished on the [`file-icons`](https://github.com/DanBrooker/file-icons) package, then I'll make a bee-line for this. I've already made a start.

I have the worst track record of starting projects and putting them down to start another...

**Comment by bronson** [comment]
No worries, I really like file-icons too.  Gotta admit, given the popularity difference between roff and icons, your time might be better spent over there.  :)

**Comment by Alhadis** [comment]
Alright, [all done](https://github.com/DanBrooker/file-icons/releases/tag/v2.0.0)! Lot of work, as you can see. Now then... let's get some `roff` happenin'. :)

**EDIT:** Okay, erm, maybe later. I spoke too soon... bloody Nuclide. :(

**Comment by arbourd** [comment]
Hey @Alhadis, would this be part of the package or are you working on a separate package? Are you accepting pull requests?

**Comment by Alhadis** [comment]
I'm making every effort to get around to it, but so far I've had to fight through urgent crap with `file-icons`. All concerning things outside my control:

1. Updated `file-icons` to not break from jQuery removal in core packages
2. Separated filesystem API so weird compatibility bugs can be investigated easier
3. Now republishing a module because I found I had to deal with [this shit](https://github.com/atom/apm/issues/702) at the last minute (literally):

<img src="https://cloud.githubusercontent.com/assets/2346707/24156295/48b8d744-0eaa-11e7-9b4f-095905caaa20.png" width="410" alt="Fuck APM" />

4. Meanwhile, the release notes of `file-icons v2.1.0` are [chillin'  there](https://github.com/file-icons/atom/releases/tag/v2.1.0) rather awkwardly waiting to be visible to the Atom community. Stuff like this happening all the time, for weeks. I'm doing all I can to get around to this, it's my incentive for tolerance.

No pull-requests, sorry. I'm way too much of a control freak; and this is actually really complicated, but it's just a matter of focus. It'll be in this package, don't worry.

**Comment by arbourd** [comment]
Thanks for the immediate response! 

No worries. I appreciate the effort you make towards the Atom community. G'luck with `file-icons`. :)

**Comment by Alhadis** [comment]
On the plus side, guess what? The roff-preview will be a full-blown real-time renderer for `groff`, capable of displaying actual typeset output.

It's not like it's avoidable. Due to the way `troff` defines output devices, it had to be done. Figure I may as well make this damn worth the effort.

**Comment by Alhadis** [comment]
@arbourd You can track progress on the [`renderer`](https://github.com/Alhadis/language-roff/tree/renderer) branch. =) [As you can see](https://github.com/Alhadis/language-roff/blob/8a5d6aa/lib/tokeniser.js#L128-L185), it's... uh, quite involved.

**Bonus:** Will be able to convert tokenised output as SVG and Markdown. So far, so good. Shit is rock-solid.

**Comment by Alhadis** [comment]
[Halfway there](https://cdn.rawgit.com/Alhadis/language-roff/a7c07744a9d44adf32a546646f7a8d57d52e6e58/preview-tty.html). =)

**EDIT:** More than halfway:

<img src="https://cloud.githubusercontent.com/assets/2346707/25514878/732e09ea-2c23-11e7-97ea-9674d3845dd1.png" width="700" alt="Figure 1" />

**Comment by Alhadis** [comment]
@arbourd Are you good with maths and/or trigonometry? I, erm, need help. I'm [dyscalculic](https://en.wikipedia.org/wiki/Dyscalculia), and stuck on figuring out [arc-drawing](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/arc).

E.g., this code:
~~~
.PS
"+" at 0,0
arc -> from 0.5,0 to 0,0.5
arc -> cw from 0,0 to 1,0.5
arc -> cw from 0,0 to 2,0 rad 15
.PE
~~~

... should look like this in the previewer:
<img src="https://cloud.githubusercontent.com/assets/2346707/25515071/4bc46870-2c25-11e7-9883-9248e4b4aa68.png" width="255" alt="Figure 1" />

Instead, it's currently looking like this:
<img src="https://cloud.githubusercontent.com/assets/2346707/25515084/5d84eed6-2c25-11e7-8cdd-bdb65f7804e9.png" width="290" alt="Figure 2" />

I only have these coordinates to go by:
* `startX, startY` - Coordinates of the arc's starting point
* `centreX, centreY` - Coordinates of the arc's centre
* `endX, endY` - Coordinates of the arc's terminal point

But the canvas [`arc`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/arc) requires all of these:
* `x` - The x coordinate of the arc's centre.
* `y` - The y coordinate of the arc's centre.
* `radius` - The arc's radius.
* `startAngle` - The angle at which the arc starts, measured clockwise from the positive x axis and expressed in radians.
* `endAngle` - The angle at which the arc ends, measured clockwise from the positive x axis and expressed in radians.

The part with radii and angles is what's killing me... 😢

**Comment by tmpdubz** [comment]
Hi @Alhadis! I'm a friend of @arbourd and also a mathematician. I present a solution if you still require it!

That being said...

Alright! Euclidean Geometry! Game on!

So you've got a few things going on here, I'm sure you've figured out that...

1. the radius is: sqrt((startX - centreX)^2 + (startY - centreY)^2)
(or you could use end* in place of start*)

2. Now for the angles!

You'll need a way to compute the angle measured clockwise from the x-axis for any general point.

Luckily, you have inverse trig functions!

(I did my test calculations with atan2: [https://en.wikipedia.org/wiki/Atan2])

Let's set this up a bit first: 

If tan(theta) = y/x, then the inverse trig function arctan(y/x) = theta, you have 2 points, so that doesn't work as arctan will only accept 1 point as an argument and give you back the angle from the x-axis. 

You'll need to do the following computation for both the start point and the end point. 

Begin by translating the non-centre point by the same transformation you would apply to bring the centre of the circle to the origin:

***
startXnew = (startX - centreX)
startYnew = (startY - centreY)

Then compute arcttan(startYnew / startXnew), this is your startAngle.
***

As stated before, the same process applies for the end angle.

CAVEAT! arctan is periodic, so if your arc crosses the positive x axis, there is a chance that you may get some odd behaviours. If this is the case, and it gives you trouble, I'd be happy to help.

I hope this was clear and helpful and not too excessive! Best of luck!

**Comment by Alhadis** [comment]
Oh wow, thank you! This was much more help than I expected... and a lot for my poor little head to take in, but I'm trying. Some generous folks on Groff's mailing list have also extended their help. I'm going through everything now, but plotting it on paper to help me visualise it.

[Dyscalculia](https://en.wikipedia.org/wiki/Dyscalculia) is part of what's making this so hard... 😢 The numbers in my head keep "slipping" when I try to follow them, so I keep getting lost in people's explanations.

I'll update once I finally figure this out... thank you so much again!!

**Comment by Alhadis** [comment]
Right, finally realised why I've spent so long deliberating on implementation decisions. I've been developing two distinct projects in tandem with one another.

Say hello to [Electroff](https://github.com/Alhadis/Electroff). JavaScript-based Troff integration. It'll be worked into the Atom package as a dependency. Dunno if it'll be published to NPM under that name, though... because it's not strictly Electron-specific.

Anyway, we'll see. Need to get `v1.3.0` released first, it's almost been a freaking year. ;p

**EDIT:** Okay, yeah, erh... better give that module a less wanky name...

**Comment by TriMoon** [comment]
So how do we get to see previews of man pages?
I just installed this package in my atom-beta and don't see any options to preview the file i'm editing...
Any progress yet? :smile_cat: 

**edit:** Nevermind, i found the "save-as" option finally...
This needs to change into a preview-pane with generated file in a tmp dir that gets updated/removed as you edit ofcourse i bet :wink:

**Comment by Alhadis** [comment]
It's literally nearing completion. Work on this is taking place over at the [Roff.js](https://github.com/Alhadis/Roff.js) repository, where I'm wrapping up surface-level APIs for loading and formatting files with `groff` (and by extension, `man`).

Everything is ready to go, it's really just me bikeshedding with myself and being a perfectionist. If you want a glimpse of what you'll be getting, you can checkout the Roff.js repository, and run [`electron`](https://www.npmjs.com/package/electron) on [`test/demos/canvas/umd.html`](https://github.com/Alhadis/Roff.js/blob/1c3ad9ab382fd7909947cf4d90bb32170b419704/test/demos/canvas/umd.html). You'll get something like this:

<img src="https://user-images.githubusercontent.com/2346707/61463914-b3f89480-a9b8-11e9-915e-21b7d6d1742e.jpg" alt="Figure 1" />

... which is what a man page is *supposed* to look like. 😉 However, since we're all used to seeing them formatted for terminal display, you'll probably expect this instead:

<img src="https://user-images.githubusercontent.com/2346707/61465127-ce337200-a9ba-11e9-8ab3-4febac6d53cf.png" alt="Figure 2" />

Obviously, that'll be supported as an alternate display mode, but as you can see, it does little to show what Troff is really capable of... 😉

**Comment by Alhadis** [comment]
There's an absurd amount of improvements, bug fixes, and features that've been added to `language-roff` since its last published release... which, erm, was back in February 2017. Before this project snowballed out of control and became worthy of a full-blown library of its own.

I've been itching for years to cut a release, but the current state of the master branch kinda blocks me from cutting one until the preview feature is finished. Which I've sworn to get done this year. Honest. 😅 The amount of work I've put into this project is unreal.

**Comment by Alhadis** [comment]
Right, so I vowed to get this finished sometime this *decade*, and because I'm still having troubles with live-reloading, I've finally done what any sane developer would have already done long ago — release now, iterate upon it later. Something my completionist self doesn't understand very well.

You'll be able to view man pages inside Atom, but edits to Roff files won't show up in the preview automatically (long story short: Atom's APIs don't make it easy for implementing live views). Will probably fix this in a future release.

**Comment by bronson** [comment]
Still amazing work! Happy new decade. 🎉

**Comment by Alhadis** [comment]
> Happy new decade. 🎉

First COVID-19, then the BLM riots, and now war between Russia and Ukraine.

We sure jinxed the _shit_ out of this decade, huh?
